version: "3"
services:
  rabbit:
    container_name: rmc-rabbitmq
    image: rabbitmq:3.8.8-management # matching CloudAMQP version
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: rmc
      RABBITMQ_DEFAULT_PASS: rmc
      RABBITMQ_DEFAULT_VHOST: rmc
    ports:
      - 5672:5672
      - 15672:15672

  postgres:
    container_name: rmc-postgres
    image: postgres:11.8 # matching ElephantSQL version
    restart: always
    environment:
      POSTGRES_DB: "rmc"
      POSTGRES_PASSWORD: "rmc"
      POSTGRES_USER: "rmc"
    ports:
      - 5432:5432

  redis:
    container_name: rmc-redis
    image: redis:6.0.5 # matching Redislab version
    restart: always
    command: [
        "bash",
        "-c",
        "
        docker-entrypoint.sh
        --requirepass rmc
        --appendonly yes
        ",
      ]
    ports:
      - 6379:6379

  api:
    container_name: api
    depends_on:
      - postgres
      - redis
      - rabbit
    image: golang:1.15.3-alpine
    volumes:
      - .:/go/src/rmc
    working_dir: /go/src/rmc
    command: go run ./cmd/api
    restart: always
    ports:
      - 42069:42069

  task:
    container_name: task
    depends_on:
      - postgres
      - rabbit
    image: golang:1.15.3-alpine
    volumes:
      - .:/go/src/rmc
    working_dir: /go/src/rmc
    command: go run ./cmd/task
    restart: always

  worker:
    container_name: worker
    depends_on:
      - rabbit
    image: golang:1.15.3-alpine
    volumes:
      - .:/go/src/rmc
      - /var/run/docker.sock:/var/run/docker.sock # FOR TESTING ONLY, DON'T ACTUALLY RUN IT IN PRODUCTION
    working_dir: /go/src/rmc
    command: go run ./cmd/worker
    restart: always
