version: "3"
networks:
  rmc-multi:

services:
  rabbit:
    container_name: rmc-rabbitmq
    image: rabbitmq:3.8.8-management # matching CloudAMQP version
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: rmc
      RABBITMQ_DEFAULT_PASS: rmc
      RABBITMQ_DEFAULT_VHOST: rmc
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      rmc-multi:

  crdb:
    container_name: rmc-crdb
    image: cockroachdb/cockroach:latest
    volumes:
      - ./crdb:/cockroach/cockroach-data
    command: start --insecure --listen-addr=0.0.0.0
    ports:
      - "26257:26257"
      - "8080:8080"
    networks:
      rmc-multi:

  redis:
    container_name: rmc-redis
    image: redis:6.0.5 # matching Redislab version
    restart: always
    command: [
        "bash",
        "-c",
        "
        docker-entrypoint.sh
        --requirepass rmc
        --appendonly yes
        ",
      ]
    ports:
      - 6379:6379
    networks:
      rmc-multi:

  api:
    container_name: api
    depends_on:
      - crdb
      - redis
      - rabbit
    image: rmc-api
    volumes:
      - .:/go/src/rmc
    working_dir: /go/src/rmc
    restart: always
    ports:
      - 42069:42069
    networks:
      rmc-multi:

  task1:
    container_name: task-replica-1
    depends_on:
      - crdb
      - rabbit
    image: rmc-task
    volumes:
      - .:/go/src/rmc
    working_dir: /go/src/rmc
    restart: always
    networks:
      rmc-multi:

  task2:
    container_name: task-replica-2
    depends_on:
      - crdb
      - rabbit
    image: rmc-task
    volumes:
      - .:/go/src/rmc
    working_dir: /go/src/rmc
    restart: always
    networks:
      rmc-multi:

  worker-elaborate-sim:
    container_name: worker-test
    depends_on:
      - rabbit
    image: rmc-worker
    volumes:
      - .:/go/src/rmc
      - /var/run/docker.sock:/var/run/docker.sock # FOR TESTING ONLY, DON'T ACTUALLY RUN IT IN PRODUCTION
    working_dir: /go/src/rmc
    restart: always
    environment:
      HOST_NAME: "elaborate-sim"
    networks:
      rmc-multi:

  worker-floral-spring:
    container_name: worker-floral-spring
    depends_on:
      - rabbit
    image: rmc-worker
    volumes:
      - .:/go/src/rmc
      - /var/run/docker.sock:/var/run/docker.sock # FOR TESTING ONLY, DON'T ACTUALLY RUN IT IN PRODUCTION
    working_dir: /go/src/rmc
    restart: always
    environment:
      HOST_NAME: "floral-spring"
    networks:
      rmc-multi:

  worker-liquid-heart:
    container_name: worker-liquid-heart
    depends_on:
      - rabbit
    image: rmc-worker
    volumes:
      - .:/go/src/rmc
      - /var/run/docker.sock:/var/run/docker.sock # FOR TESTING ONLY, DON'T ACTUALLY RUN IT IN PRODUCTION
    working_dir: /go/src/rmc
    restart: always
    environment:
      HOST_NAME: "liquid-heart"
    networks:
      rmc-multi:
