// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.2
// source: spec/protocol/instance.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ControlRequest_ControlAction int32

const (
	ControlRequest_UNKNOWN ControlRequest_ControlAction = 0
	ControlRequest_START   ControlRequest_ControlAction = 1
	ControlRequest_STOP    ControlRequest_ControlAction = 2
)

// Enum value maps for ControlRequest_ControlAction.
var (
	ControlRequest_ControlAction_name = map[int32]string{
		0: "UNKNOWN",
		1: "START",
		2: "STOP",
	}
	ControlRequest_ControlAction_value = map[string]int32{
		"UNKNOWN": 0,
		"START":   1,
		"STOP":    2,
	}
)

func (x ControlRequest_ControlAction) Enum() *ControlRequest_ControlAction {
	p := new(ControlRequest_ControlAction)
	*p = x
	return p
}

func (x ControlRequest_ControlAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControlRequest_ControlAction) Descriptor() protoreflect.EnumDescriptor {
	return file_spec_protocol_instance_proto_enumTypes[0].Descriptor()
}

func (ControlRequest_ControlAction) Type() protoreflect.EnumType {
	return &file_spec_protocol_instance_proto_enumTypes[0]
}

func (x ControlRequest_ControlAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControlRequest_ControlAction.Descriptor instead.
func (ControlRequest_ControlAction) EnumDescriptor() ([]byte, []int) {
	return file_spec_protocol_instance_proto_rawDescGZIP(), []int{1, 0}
}

type ControlReply_ControlResult int32

const (
	ControlReply_UNKNOWN ControlReply_ControlResult = 0
	ControlReply_SUCCESS ControlReply_ControlResult = 1
	ControlReply_FAILURE ControlReply_ControlResult = 2
)

// Enum value maps for ControlReply_ControlResult.
var (
	ControlReply_ControlResult_name = map[int32]string{
		0: "UNKNOWN",
		1: "SUCCESS",
		2: "FAILURE",
	}
	ControlReply_ControlResult_value = map[string]int32{
		"UNKNOWN": 0,
		"SUCCESS": 1,
		"FAILURE": 2,
	}
)

func (x ControlReply_ControlResult) Enum() *ControlReply_ControlResult {
	p := new(ControlReply_ControlResult)
	*p = x
	return p
}

func (x ControlReply_ControlResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControlReply_ControlResult) Descriptor() protoreflect.EnumDescriptor {
	return file_spec_protocol_instance_proto_enumTypes[1].Descriptor()
}

func (ControlReply_ControlResult) Type() protoreflect.EnumType {
	return &file_spec_protocol_instance_proto_enumTypes[1]
}

func (x ControlReply_ControlResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControlReply_ControlResult.Descriptor instead.
func (ControlReply_ControlResult) EnumDescriptor() ([]byte, []int) {
	return file_spec_protocol_instance_proto_rawDescGZIP(), []int{2, 0}
}

type ProvisionRequest_ProvisionAction int32

const (
	ProvisionRequest_UNKNOWN ProvisionRequest_ProvisionAction = 0
	ProvisionRequest_CREATE  ProvisionRequest_ProvisionAction = 1
	ProvisionRequest_DELETE  ProvisionRequest_ProvisionAction = 2
)

// Enum value maps for ProvisionRequest_ProvisionAction.
var (
	ProvisionRequest_ProvisionAction_name = map[int32]string{
		0: "UNKNOWN",
		1: "CREATE",
		2: "DELETE",
	}
	ProvisionRequest_ProvisionAction_value = map[string]int32{
		"UNKNOWN": 0,
		"CREATE":  1,
		"DELETE":  2,
	}
)

func (x ProvisionRequest_ProvisionAction) Enum() *ProvisionRequest_ProvisionAction {
	p := new(ProvisionRequest_ProvisionAction)
	*p = x
	return p
}

func (x ProvisionRequest_ProvisionAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProvisionRequest_ProvisionAction) Descriptor() protoreflect.EnumDescriptor {
	return file_spec_protocol_instance_proto_enumTypes[2].Descriptor()
}

func (ProvisionRequest_ProvisionAction) Type() protoreflect.EnumType {
	return &file_spec_protocol_instance_proto_enumTypes[2]
}

func (x ProvisionRequest_ProvisionAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProvisionRequest_ProvisionAction.Descriptor instead.
func (ProvisionRequest_ProvisionAction) EnumDescriptor() ([]byte, []int) {
	return file_spec_protocol_instance_proto_rawDescGZIP(), []int{3, 0}
}

type ProvisionReply_ProvisionResult int32

const (
	ProvisionReply_UNKNOWN ProvisionReply_ProvisionResult = 0
	ProvisionReply_SUCCESS ProvisionReply_ProvisionResult = 1
	ProvisionReply_FAILURE ProvisionReply_ProvisionResult = 2
)

// Enum value maps for ProvisionReply_ProvisionResult.
var (
	ProvisionReply_ProvisionResult_name = map[int32]string{
		0: "UNKNOWN",
		1: "SUCCESS",
		2: "FAILURE",
	}
	ProvisionReply_ProvisionResult_value = map[string]int32{
		"UNKNOWN": 0,
		"SUCCESS": 1,
		"FAILURE": 2,
	}
)

func (x ProvisionReply_ProvisionResult) Enum() *ProvisionReply_ProvisionResult {
	p := new(ProvisionReply_ProvisionResult)
	*p = x
	return p
}

func (x ProvisionReply_ProvisionResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProvisionReply_ProvisionResult) Descriptor() protoreflect.EnumDescriptor {
	return file_spec_protocol_instance_proto_enumTypes[3].Descriptor()
}

func (ProvisionReply_ProvisionResult) Type() protoreflect.EnumType {
	return &file_spec_protocol_instance_proto_enumTypes[3]
}

func (x ProvisionReply_ProvisionResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProvisionReply_ProvisionResult.Descriptor instead.
func (ProvisionReply_ProvisionResult) EnumDescriptor() ([]byte, []int) {
	return file_spec_protocol_instance_proto_rawDescGZIP(), []int{4, 0}
}

// Instance describes the a Minecraft server
type Instance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InstanceID string      `protobuf:"bytes,1,opt,name=InstanceID,proto3" json:"InstanceID,omitempty"`
	Host       string      `protobuf:"bytes,2,opt,name=Host,proto3" json:"Host,omitempty"`
	Parameters *Parameters `protobuf:"bytes,10,opt,name=Parameters,proto3" json:"Parameters,omitempty"`
}

func (x *Instance) Reset() {
	*x = Instance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_protocol_instance_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Instance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instance) ProtoMessage() {}

func (x *Instance) ProtoReflect() protoreflect.Message {
	mi := &file_spec_protocol_instance_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instance.ProtoReflect.Descriptor instead.
func (*Instance) Descriptor() ([]byte, []int) {
	return file_spec_protocol_instance_proto_rawDescGZIP(), []int{0}
}

func (x *Instance) GetInstanceID() string {
	if x != nil {
		return x.InstanceID
	}
	return ""
}

func (x *Instance) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Instance) GetParameters() *Parameters {
	if x != nil {
		return x.Parameters
	}
	return nil
}

// ControlRequest contains a request to start/stop an instance
type ControlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Instance *Instance                    `protobuf:"bytes,1,opt,name=Instance,proto3" json:"Instance,omitempty"`
	Action   ControlRequest_ControlAction `protobuf:"varint,10,opt,name=Action,proto3,enum=protocol.ControlRequest_ControlAction" json:"Action,omitempty"`
}

func (x *ControlRequest) Reset() {
	*x = ControlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_protocol_instance_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlRequest) ProtoMessage() {}

func (x *ControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spec_protocol_instance_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlRequest.ProtoReflect.Descriptor instead.
func (*ControlRequest) Descriptor() ([]byte, []int) {
	return file_spec_protocol_instance_proto_rawDescGZIP(), []int{1}
}

func (x *ControlRequest) GetInstance() *Instance {
	if x != nil {
		return x.Instance
	}
	return nil
}

func (x *ControlRequest) GetAction() ControlRequest_ControlAction {
	if x != nil {
		return x.Action
	}
	return ControlRequest_UNKNOWN
}

// ControlReply contains the outcome of a previous control request
type ControlReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Instance      *Instance                    `protobuf:"bytes,1,opt,name=Instance,proto3" json:"Instance,omitempty"`
	RequestAction ControlRequest_ControlAction `protobuf:"varint,2,opt,name=RequestAction,proto3,enum=protocol.ControlRequest_ControlAction" json:"RequestAction,omitempty"`
	Result        ControlReply_ControlResult   `protobuf:"varint,10,opt,name=Result,proto3,enum=protocol.ControlReply_ControlResult" json:"Result,omitempty"`
}

func (x *ControlReply) Reset() {
	*x = ControlReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_protocol_instance_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ControlReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlReply) ProtoMessage() {}

func (x *ControlReply) ProtoReflect() protoreflect.Message {
	mi := &file_spec_protocol_instance_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlReply.ProtoReflect.Descriptor instead.
func (*ControlReply) Descriptor() ([]byte, []int) {
	return file_spec_protocol_instance_proto_rawDescGZIP(), []int{2}
}

func (x *ControlReply) GetInstance() *Instance {
	if x != nil {
		return x.Instance
	}
	return nil
}

func (x *ControlReply) GetRequestAction() ControlRequest_ControlAction {
	if x != nil {
		return x.RequestAction
	}
	return ControlRequest_UNKNOWN
}

func (x *ControlReply) GetResult() ControlReply_ControlResult {
	if x != nil {
		return x.Result
	}
	return ControlReply_UNKNOWN
}

// ProvisionRequest contains a request to create/delete an instance
type ProvisionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Instance *Instance                        `protobuf:"bytes,1,opt,name=Instance,proto3" json:"Instance,omitempty"`
	Action   ProvisionRequest_ProvisionAction `protobuf:"varint,10,opt,name=Action,proto3,enum=protocol.ProvisionRequest_ProvisionAction" json:"Action,omitempty"`
}

func (x *ProvisionRequest) Reset() {
	*x = ProvisionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_protocol_instance_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProvisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionRequest) ProtoMessage() {}

func (x *ProvisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spec_protocol_instance_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionRequest.ProtoReflect.Descriptor instead.
func (*ProvisionRequest) Descriptor() ([]byte, []int) {
	return file_spec_protocol_instance_proto_rawDescGZIP(), []int{3}
}

func (x *ProvisionRequest) GetInstance() *Instance {
	if x != nil {
		return x.Instance
	}
	return nil
}

func (x *ProvisionRequest) GetAction() ProvisionRequest_ProvisionAction {
	if x != nil {
		return x.Action
	}
	return ProvisionRequest_UNKNOWN
}

// ProvisionReply contains the outcome of a previous provision request
type ProvisionReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Instance      *Instance                        `protobuf:"bytes,1,opt,name=Instance,proto3" json:"Instance,omitempty"`
	RequestAction ProvisionRequest_ProvisionAction `protobuf:"varint,2,opt,name=RequestAction,proto3,enum=protocol.ProvisionRequest_ProvisionAction" json:"RequestAction,omitempty"`
	Result        ProvisionReply_ProvisionResult   `protobuf:"varint,10,opt,name=Result,proto3,enum=protocol.ProvisionReply_ProvisionResult" json:"Result,omitempty"`
}

func (x *ProvisionReply) Reset() {
	*x = ProvisionReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_protocol_instance_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProvisionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionReply) ProtoMessage() {}

func (x *ProvisionReply) ProtoReflect() protoreflect.Message {
	mi := &file_spec_protocol_instance_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionReply.ProtoReflect.Descriptor instead.
func (*ProvisionReply) Descriptor() ([]byte, []int) {
	return file_spec_protocol_instance_proto_rawDescGZIP(), []int{4}
}

func (x *ProvisionReply) GetInstance() *Instance {
	if x != nil {
		return x.Instance
	}
	return nil
}

func (x *ProvisionReply) GetRequestAction() ProvisionRequest_ProvisionAction {
	if x != nil {
		return x.RequestAction
	}
	return ProvisionRequest_UNKNOWN
}

func (x *ProvisionReply) GetResult() ProvisionReply_ProvisionResult {
	if x != nil {
		return x.Result
	}
	return ProvisionReply_UNKNOWN
}

var File_spec_protocol_instance_proto protoreflect.FileDescriptor

var file_spec_protocol_instance_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x73, 0x70, 0x65, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f,
	0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x1a, 0x1e, 0x73, 0x70, 0x65, 0x63, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65,
	0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x74, 0x0a, 0x08, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x6f, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x34, 0x0a, 0x0a, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65,
	0x72, 0x73, 0x52, 0x0a, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x22, 0xb3,
	0x01, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x2e, 0x0a, 0x08, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x49,
	0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x08, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x12, 0x3e, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x26, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x43, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x74,
	0x72, 0x6f, 0x6c, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0x31, 0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12,
	0x09, 0x0a, 0x05, 0x53, 0x54, 0x41, 0x52, 0x54, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x54,
	0x4f, 0x50, 0x10, 0x02, 0x22, 0x82, 0x02, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2e, 0x0a, 0x08, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x08, 0x49, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x4c, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x26, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x3c, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x43, 0x6f, 0x6e, 0x74,
	0x72, 0x6f, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x22, 0x36, 0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12,
	0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07,
	0x46, 0x41, 0x49, 0x4c, 0x55, 0x52, 0x45, 0x10, 0x02, 0x22, 0xbe, 0x01, 0x0a, 0x10, 0x50, 0x72,
	0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e,
	0x0a, 0x08, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x52, 0x08, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x42,
	0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2a,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x73,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x69,
	0x73, 0x69, 0x6f, 0x6e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x36, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e,
	0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x10, 0x01, 0x12, 0x0a,
	0x0a, 0x06, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x02, 0x22, 0x8e, 0x02, 0x0a, 0x0e, 0x50,
	0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2e, 0x0a,
	0x08, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x52, 0x08, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x50, 0x0a,
	0x0d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x2a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x50, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x2e, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x0d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x40, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x28, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x69,
	0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x73,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x22, 0x38, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10,
	0x00, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x01, 0x12, 0x0b,
	0x0a, 0x07, 0x46, 0x41, 0x49, 0x4c, 0x55, 0x52, 0x45, 0x10, 0x02, 0x42, 0x29, 0x5a, 0x27, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x7a, 0x6c, 0x6c, 0x6f, 0x76, 0x65,
	0x73, 0x75, 0x6b, 0x69, 0x2f, 0x72, 0x6d, 0x63, 0x2f, 0x73, 0x70, 0x65, 0x63, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_spec_protocol_instance_proto_rawDescOnce sync.Once
	file_spec_protocol_instance_proto_rawDescData = file_spec_protocol_instance_proto_rawDesc
)

func file_spec_protocol_instance_proto_rawDescGZIP() []byte {
	file_spec_protocol_instance_proto_rawDescOnce.Do(func() {
		file_spec_protocol_instance_proto_rawDescData = protoimpl.X.CompressGZIP(file_spec_protocol_instance_proto_rawDescData)
	})
	return file_spec_protocol_instance_proto_rawDescData
}

var file_spec_protocol_instance_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_spec_protocol_instance_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_spec_protocol_instance_proto_goTypes = []interface{}{
	(ControlRequest_ControlAction)(0),     // 0: protocol.ControlRequest.ControlAction
	(ControlReply_ControlResult)(0),       // 1: protocol.ControlReply.ControlResult
	(ProvisionRequest_ProvisionAction)(0), // 2: protocol.ProvisionRequest.ProvisionAction
	(ProvisionReply_ProvisionResult)(0),   // 3: protocol.ProvisionReply.ProvisionResult
	(*Instance)(nil),                      // 4: protocol.Instance
	(*ControlRequest)(nil),                // 5: protocol.ControlRequest
	(*ControlReply)(nil),                  // 6: protocol.ControlReply
	(*ProvisionRequest)(nil),              // 7: protocol.ProvisionRequest
	(*ProvisionReply)(nil),                // 8: protocol.ProvisionReply
	(*Parameters)(nil),                    // 9: protocol.Parameters
}
var file_spec_protocol_instance_proto_depIdxs = []int32{
	9,  // 0: protocol.Instance.Parameters:type_name -> protocol.Parameters
	4,  // 1: protocol.ControlRequest.Instance:type_name -> protocol.Instance
	0,  // 2: protocol.ControlRequest.Action:type_name -> protocol.ControlRequest.ControlAction
	4,  // 3: protocol.ControlReply.Instance:type_name -> protocol.Instance
	0,  // 4: protocol.ControlReply.RequestAction:type_name -> protocol.ControlRequest.ControlAction
	1,  // 5: protocol.ControlReply.Result:type_name -> protocol.ControlReply.ControlResult
	4,  // 6: protocol.ProvisionRequest.Instance:type_name -> protocol.Instance
	2,  // 7: protocol.ProvisionRequest.Action:type_name -> protocol.ProvisionRequest.ProvisionAction
	4,  // 8: protocol.ProvisionReply.Instance:type_name -> protocol.Instance
	2,  // 9: protocol.ProvisionReply.RequestAction:type_name -> protocol.ProvisionRequest.ProvisionAction
	3,  // 10: protocol.ProvisionReply.Result:type_name -> protocol.ProvisionReply.ProvisionResult
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_spec_protocol_instance_proto_init() }
func file_spec_protocol_instance_proto_init() {
	if File_spec_protocol_instance_proto != nil {
		return
	}
	file_spec_protocol_parameters_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_spec_protocol_instance_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Instance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_protocol_instance_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ControlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_protocol_instance_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ControlReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_protocol_instance_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProvisionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_protocol_instance_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProvisionReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_spec_protocol_instance_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spec_protocol_instance_proto_goTypes,
		DependencyIndexes: file_spec_protocol_instance_proto_depIdxs,
		EnumInfos:         file_spec_protocol_instance_proto_enumTypes,
		MessageInfos:      file_spec_protocol_instance_proto_msgTypes,
	}.Build()
	File_spec_protocol_instance_proto = out.File
	file_spec_protocol_instance_proto_rawDesc = nil
	file_spec_protocol_instance_proto_goTypes = nil
	file_spec_protocol_instance_proto_depIdxs = nil
}
